name: azure container apps
 
on:
  push:
    branches:
      - main
 
env:
  AZURE_RESOURCE_GROUP: backend
  BLOB_STORAGE_ACCOUNT_NAME: accountingmonk
  
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
     # Authentication
    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set Azure Container Apps context
      uses: azure/container-apps-set-context@v1
      with:
        resource-group-name: githubactions
        instance-name: githubactionscicd

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy@v1
      with:
        image: sudalaivj/backend:v2
        port: 80